site_name: Firefox Lockbox for Android
site_description: Documentation for Firefox Lockbox for Android application
theme: readthedocs
repo_name: GitHub
repo_url: https://github.com/mozilla-lockbox/lockbox-android

pages:
- 'Introduction': 'index.md'
- 'Contributing': 'contributing.md'
- 'Architecture':
  - 'Using Keys and Biometrics': 'architecture/sec-apis.md'
- 'Developer Guides':
  - 'Build and Install': 'install.md'
